language: node_js
node_js:
  - "v9.5.0"

env:
     - DATABASE_URL=postgresql://coder:coder123@localhost/greet-test
    
before_script:
  - psql -c 'create database greet-test;' -U postgres
  - psql -U postgres -d greet-test -a -f table.sql

addons:
    apt:
    packages:
    - postgresql-server-dev-9.2